name: CI

on:
  pull_request:
  push:
    branches: ['**'] # build for all branches
    tags-ignore: ['**'] # do not build on tag creation

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.14

    steps:
      - uses: actions/checkout@v4

      - uses: coursier/cache-action@v6

      - name: setup Java and SBT
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'sbt'

      - name: Check code formatting
        run: sbt check

      - name: build ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean coverage test

      - name: test coverage
        if: success()
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: sbt ++${{ matrix.scala }} coverageReport coverageAggregate coveralls
